/* eslint-disable */
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = {
  [_ in K]?: never;
};
export type Incremental<T> =
  | T
  | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string };
  String: { input: string; output: string };
  Boolean: { input: boolean; output: boolean };
  Int: { input: number; output: number };
  Float: { input: number; output: number };
  /** Represents non-fractional signed whole numeric values. Since the value may exceed the size of a 32-bit integer, it's encoded as a string. */
  BigInt: { input: any; output: any };
};

export enum NumberSign {
  Negative = 'NEGATIVE',
  Positive = 'POSITIVE',
}

export type SandboxBookmark = {
  documentId: Scalars['String']['input'];
  userId: Scalars['String']['input'];
};

/** Autogenerated input type of SandboxTest */
export type SandboxTestInput = {
  attributes: SandboxBookmark;
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
};

export type GetCompanyFinancialStatementsByCodesQueryVariables = Exact<{
  stockCodes?: InputMaybe<Array<Scalars['String']['input']> | Scalars['String']['input']>;
}>;

export type GetCompanyFinancialStatementsByCodesQuery = {
  __typename?: 'Query';
  companyFinancialStatements?: Array<{
    __typename?: 'CompanyFinancialStatement';
    fiscalYearStartDate?: string | null;
    fiscalYearEndDate?: string | null;
    filingDate?: string | null;
    stockCode?: string | null;
    companyJapaneseName?: string | null;
    hasConsolidatedFinancialStatement?: boolean | null;
    consolidatedInductoryCode?: string | null;
    nonConsolidatedInductoryCode?: string | null;
    balanceSheet?: {
      __typename?: 'BalanceSheet';
      amount?: {
        __typename?: 'BalanceSheetAmount';
        currentAsset?: any | null;
        propertyPlantAndEquipment?: any | null;
        intangibleAsset?: any | null;
        investmentAndOtherAsset?: any | null;
        currentLiability?: any | null;
        noncurrentLiability?: any | null;
        netAsset?: any | null;
      } | null;
      ratio?: {
        __typename?: 'BalanceSheetRatio';
        currentAsset?: number | null;
        propertyPlantAndEquipment?: number | null;
        intangibleAsset?: number | null;
        investmentAndOtherAsset?: number | null;
        currentLiability?: number | null;
        noncurrentLiability?: number | null;
        netAsset?: number | null;
      } | null;
    } | null;
    profitLoss?: {
      __typename?: 'ProfitLoss';
      amount?: {
        __typename?: 'ProfitLossAmount';
        netSales?: any | null;
        originalCost?: any | null;
        sellingGeneralExpense?: any | null;
        operatingIncome?: any | null;
      } | null;
      ratio?: {
        __typename?: 'ProfitLossRatio';
        netSales?: number | null;
        originalCost?: number | null;
        sellingGeneralExpense?: number | null;
        operatingIncome?: number | null;
      } | null;
    } | null;
    cashFlow?: {
      __typename?: 'CashFlow';
      startingCash?: any | null;
      operatingActivitiesCashFlow?: any | null;
      investingActivitiesCashFlow?: any | null;
      financingActivitiesCashFlow?: any | null;
      endingCash?: any | null;
    } | null;
  }> | null;
};

export const GetCompanyFinancialStatementsByCodesDocument = {
  kind: 'Document',
  definitions: [
    {
      kind: 'OperationDefinition',
      operation: 'query',
      name: { kind: 'Name', value: 'GetCompanyFinancialStatementsByCodes' },
      variableDefinitions: [
        {
          kind: 'VariableDefinition',
          variable: { kind: 'Variable', name: { kind: 'Name', value: 'stockCodes' } },
          type: {
            kind: 'ListType',
            type: {
              kind: 'NonNullType',
              type: { kind: 'NamedType', name: { kind: 'Name', value: 'String' } },
            },
          },
        },
      ],
      selectionSet: {
        kind: 'SelectionSet',
        selections: [
          {
            kind: 'Field',
            name: { kind: 'Name', value: 'companyFinancialStatements' },
            arguments: [
              {
                kind: 'Argument',
                name: { kind: 'Name', value: 'offset' },
                value: { kind: 'IntValue', value: '0' },
              },
              {
                kind: 'Argument',
                name: { kind: 'Name', value: 'limit' },
                value: { kind: 'IntValue', value: '100' },
              },
              {
                kind: 'Argument',
                name: { kind: 'Name', value: 'stockCodes' },
                value: { kind: 'Variable', name: { kind: 'Name', value: 'stockCodes' } },
              },
            ],
            selectionSet: {
              kind: 'SelectionSet',
              selections: [
                { kind: 'Field', name: { kind: 'Name', value: 'fiscalYearStartDate' } },
                { kind: 'Field', name: { kind: 'Name', value: 'fiscalYearEndDate' } },
                { kind: 'Field', name: { kind: 'Name', value: 'filingDate' } },
                { kind: 'Field', name: { kind: 'Name', value: 'stockCode' } },
                { kind: 'Field', name: { kind: 'Name', value: 'companyJapaneseName' } },
                {
                  kind: 'Field',
                  name: { kind: 'Name', value: 'hasConsolidatedFinancialStatement' },
                },
                { kind: 'Field', name: { kind: 'Name', value: 'consolidatedInductoryCode' } },
                { kind: 'Field', name: { kind: 'Name', value: 'nonConsolidatedInductoryCode' } },
                {
                  kind: 'Field',
                  name: { kind: 'Name', value: 'balanceSheet' },
                  selectionSet: {
                    kind: 'SelectionSet',
                    selections: [
                      {
                        kind: 'Field',
                        name: { kind: 'Name', value: 'amount' },
                        selectionSet: {
                          kind: 'SelectionSet',
                          selections: [
                            { kind: 'Field', name: { kind: 'Name', value: 'currentAsset' } },
                            {
                              kind: 'Field',
                              name: { kind: 'Name', value: 'propertyPlantAndEquipment' },
                            },
                            { kind: 'Field', name: { kind: 'Name', value: 'intangibleAsset' } },
                            {
                              kind: 'Field',
                              name: { kind: 'Name', value: 'investmentAndOtherAsset' },
                            },
                            { kind: 'Field', name: { kind: 'Name', value: 'currentLiability' } },
                            { kind: 'Field', name: { kind: 'Name', value: 'noncurrentLiability' } },
                            { kind: 'Field', name: { kind: 'Name', value: 'netAsset' } },
                          ],
                        },
                      },
                      {
                        kind: 'Field',
                        name: { kind: 'Name', value: 'ratio' },
                        selectionSet: {
                          kind: 'SelectionSet',
                          selections: [
                            { kind: 'Field', name: { kind: 'Name', value: 'currentAsset' } },
                            {
                              kind: 'Field',
                              name: { kind: 'Name', value: 'propertyPlantAndEquipment' },
                            },
                            { kind: 'Field', name: { kind: 'Name', value: 'intangibleAsset' } },
                            {
                              kind: 'Field',
                              name: { kind: 'Name', value: 'investmentAndOtherAsset' },
                            },
                            { kind: 'Field', name: { kind: 'Name', value: 'currentLiability' } },
                            { kind: 'Field', name: { kind: 'Name', value: 'noncurrentLiability' } },
                            { kind: 'Field', name: { kind: 'Name', value: 'netAsset' } },
                          ],
                        },
                      },
                    ],
                  },
                },
                {
                  kind: 'Field',
                  name: { kind: 'Name', value: 'profitLoss' },
                  selectionSet: {
                    kind: 'SelectionSet',
                    selections: [
                      {
                        kind: 'Field',
                        name: { kind: 'Name', value: 'amount' },
                        selectionSet: {
                          kind: 'SelectionSet',
                          selections: [
                            { kind: 'Field', name: { kind: 'Name', value: 'netSales' } },
                            { kind: 'Field', name: { kind: 'Name', value: 'originalCost' } },
                            {
                              kind: 'Field',
                              name: { kind: 'Name', value: 'sellingGeneralExpense' },
                            },
                            { kind: 'Field', name: { kind: 'Name', value: 'operatingIncome' } },
                          ],
                        },
                      },
                      {
                        kind: 'Field',
                        name: { kind: 'Name', value: 'ratio' },
                        selectionSet: {
                          kind: 'SelectionSet',
                          selections: [
                            { kind: 'Field', name: { kind: 'Name', value: 'netSales' } },
                            { kind: 'Field', name: { kind: 'Name', value: 'originalCost' } },
                            {
                              kind: 'Field',
                              name: { kind: 'Name', value: 'sellingGeneralExpense' },
                            },
                            { kind: 'Field', name: { kind: 'Name', value: 'operatingIncome' } },
                          ],
                        },
                      },
                    ],
                  },
                },
                {
                  kind: 'Field',
                  name: { kind: 'Name', value: 'cashFlow' },
                  selectionSet: {
                    kind: 'SelectionSet',
                    selections: [
                      { kind: 'Field', name: { kind: 'Name', value: 'startingCash' } },
                      {
                        kind: 'Field',
                        name: { kind: 'Name', value: 'operatingActivitiesCashFlow' },
                      },
                      {
                        kind: 'Field',
                        name: { kind: 'Name', value: 'investingActivitiesCashFlow' },
                      },
                      {
                        kind: 'Field',
                        name: { kind: 'Name', value: 'financingActivitiesCashFlow' },
                      },
                      { kind: 'Field', name: { kind: 'Name', value: 'endingCash' } },
                    ],
                  },
                },
              ],
            },
          },
        ],
      },
    },
  ],
} as unknown as DocumentNode<
  GetCompanyFinancialStatementsByCodesQuery,
  GetCompanyFinancialStatementsByCodesQueryVariables
>;
